source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'PhoneWorld' do
pod 'AFNetworking', '~> 3.0'
pod 'JSONModel'
pod 'SDWebImage'
pod 'SVPullToRefresh'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'Masonry'
pod 'SDCycleScrollView','~> 1.64'
pod 'IQKeyboardManager'
pod 'MJRefresh'
end
